version: '3.8'

services:
  db:
    image: docker.arvancloud.ir/postgres:15-alpine
    container_name: quiz-game-db
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-game-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    container_name: quiz-game-backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-game-network

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    container_name: quiz-game-frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - quiz-game-network

networks:
  quiz-game-network:
    driver: bridge

volumes:
  postgres_data:
